<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TambahLombaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('tambah_lomba')->insert([
            // [
            //     'nama_lomba' => 'Lomba Inovasi Teknologi 2024',
            //     'kategori_lomba' => 'Teknologi',
            //     'tingkat_lomba' => 'nasional',
            //     'penyelenggara_lomba' => 'Kementerian Riset dan Teknologi',
            //     'deskripsi' => 'Kompetisi pengembangan teknologi inovatif untuk mahasiswa seluruh Indonesia.',
            //     'tanggal_mulai' => '2024-09-01',
            //     'tanggal_selesai' => '2024-10-01',
            //     'pamflet_lomba' => 'inovasi_tekno_2024.jpg',
            //     'status_verifikasi' => 'Disetujui',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'nama_lomba' => 'Web Development Challenge 2024',
            //     'kategori_lomba' => 'Pemrograman',
            //     'tingkat_lomba' => 'lokal',
            //     'penyelenggara_lomba' => 'Jurusan TI Polinema',
            //     'deskripsi' => 'Kompetisi membuat aplikasi berbasis web bagi mahasiswa Polinema.',
            //     'tanggal_mulai' => '2024-07-10',
            //     'tanggal_selesai' => '2024-07-20',
            //     'pamflet_lomba' => 'web_dev_challenge.jpg',
            //     'status_verifikasi' => 'Pending',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
                [
                    'nama_lomba' => 'Lomba Inovasi Teknologi 2024',
                    'kategori_lomba' => 'akademik',
                    'tingkat_lomba' => 'nasional',
                    'penyelenggara_lomba' => 'Kementerian Riset dan Teknologi',
                    'deskripsi' => 'Kompetisi pengembangan teknologi inovatif untuk mahasiswa seluruh Indonesia.',
                    'tanggal_mulai' => '2025-05-01',
                    'tanggal_selesai' => '2025-09-01', // +3 bulan dari 18 Juni 2025
                    'pamflet_lomba' => 'inovasi_tekno_2024.jpg',
                    'link_pendaftaran' => 'https://inovasi.ristek.go.id',
                    'status_verifikasi' => 'Disetujui',
                    'biaya_pendaftaran' => 0,
                    'hadiah' => 10000000,
                    'format_lomba' => 'online',
                    'tipe_lomba' => 'tim',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'user_id' => 1
                ],
                [
                    'nama_lomba' => 'Hackathon Politeknik Nasional',
                    'kategori_lomba' => 'akademik',
                    'tingkat_lomba' => 'politeknik',
                    'penyelenggara_lomba' => 'Komunitas Developer Politeknik',
                    'deskripsi' => 'Lomba pengembangan aplikasi berbasis web dan mobile untuk solusi digital kampus.',
                    'tanggal_mulai' => '2025-04-20',
                    'tanggal_selesai' => '2025-07-25', // +1 bulan dari 18 Juni 2025
                    'pamflet_lomba' => 'hackathon_poli.jpg',
                    'link_pendaftaran' => 'https://hackathon-poli.id',
                    'status_verifikasi' => 'Disetujui',
                    'biaya_pendaftaran' => 25000,
                    'hadiah' => 7000000,
                    'format_lomba' => 'offline',
                    'tipe_lomba' => 'tim',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'user_id' => 2
                ],
                [
                    'nama_lomba' => 'Cyber Security Competition 2024',
                    'kategori_lomba' => 'akademik',
                    'tingkat_lomba' => 'nasional',
                    'penyelenggara_lomba' => 'ID-CERT & Kominfo',
                    'deskripsi' => 'Ajang adu kemampuan deteksi dan penanggulangan serangan siber.',
                    'tanggal_mulai' => '2025-06-15',
                    'tanggal_selesai' => '2025-06-30', // +12 hari dari 18 Juni 2025
                    'pamflet_lomba' => 'cybersec_2024.jpg',
                    'link_pendaftaran' => 'https://cybercomp.id',
                    'status_verifikasi' => 'Disetujui',
                    'biaya_pendaftaran' => 0,
                    'hadiah' => 8000000,
                    'format_lomba' => 'online',
                    'tipe_lomba' => 'tim',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'user_id' => 1
                ],
                [
                    'nama_lomba' => 'AI & Data Science Challenge',
                    'kategori_lomba' => 'akademik',
                    'tingkat_lomba' => 'provinsi',
                    'penyelenggara_lomba' => 'AI Research Community Jatim',
                    'deskripsi' => 'Lomba pemanfaatan AI untuk prediksi dan klasifikasi berbasis dataset nyata.',
                    'tanggal_mulai' => '2025-07-05',
                    'tanggal_selesai' => '2025-07-12', // +1 minggu
                    'pamflet_lomba' => 'ai_datasci_2024.jpg',
                    'link_pendaftaran' => 'https://ai-jatim.org/challenge',
                    'status_verifikasi' => 'Disetujui',
                    'biaya_pendaftaran' => 50000,
                    'hadiah' => 5000000,
                    'format_lomba' => 'online',
                    'tipe_lomba' => 'individu',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'user_id' => 3
                ],
                [
                    'nama_lomba' => 'Mobile App Development Contest',
                    'kategori_lomba' => 'akademik',
                    'tingkat_lomba' => 'kota',
                    'penyelenggara_lomba' => 'DISKOMINFO Surabaya',
                    'deskripsi' => 'Kompetisi pembuatan aplikasi Android untuk pelayanan publik.',
                    'tanggal_mulai' => '2025-06-25',
                    'tanggal_selesai' => '2025-09-01', // +2 bulan
                    'pamflet_lomba' => 'mobile_app_contest.jpg',
                    'link_pendaftaran' => 'https://diskominfo.sby.go.id/contest',
                    'status_verifikasi' => 'Disetujui',
                    'biaya_pendaftaran' => 20000,
                    'hadiah' => 4000000,
                    'format_lomba' => 'offline',
                    'tipe_lomba' => 'individu',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'user_id' => 4
                ],
                [
                    'nama_lomba' => 'IoT Smart City Challenge',
                    'kategori_lomba' => 'akademik',
                    'tingkat_lomba' => 'nasional',
                    'penyelenggara_lomba' => 'Smart City Indonesia',
                    'deskripsi' => 'Kompetisi rancang IoT untuk solusi kota pintar berbasis sensor dan automasi.',
                    'tanggal_mulai' => '2025-07-15',
                    'tanggal_selesai' => '2025-10-15', // +3 bulan
                    'pamflet_lomba' => 'iot_smartcity.jpg',
                    'link_pendaftaran' => 'https://smartcity.id/iot',
                    'status_verifikasi' => 'Disetujui',
                    'biaya_pendaftaran' => 0,
                    'hadiah' => 10000000,
                    'format_lomba' => 'online',
                    'tipe_lomba' => 'tim',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'user_id' => 5
                ],
                [
                    'nama_lomba' => 'Website Design Competition 2024',
                    'kategori_lomba' => 'non-akademik',
                    'tingkat_lomba' => 'provinsi',
                    'penyelenggara_lomba' => 'Asosiasi Desainer Web Jatim',
                    'deskripsi' => 'Kompetisi desain antarmuka dan UX untuk website UMKM.',
                    'tanggal_mulai' => '2025-06-20',
                    'tanggal_selesai' => '2025-07-25', // +1 bulan
                    'pamflet_lomba' => 'webdesign2024.jpg',
                    'link_pendaftaran' => 'https://desainerwebjatim.org/lomba',
                    'status_verifikasi' => 'Disetujui',
                    'biaya_pendaftaran' => 30000,
                    'hadiah' => 4500000,
                    'format_lomba' => 'offline',
                    'tipe_lomba' => 'individu',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'user_id' => 2
                ],
                [
                    'nama_lomba' => 'Game Development Student Cup',
                    'kategori_lomba' => 'akademik',
                    'tingkat_lomba' => 'nasional',
                    'penyelenggara_lomba' => 'Asosiasi Game Developer Indonesia',
                    'deskripsi' => 'Turnamen pengembangan game edukatif dan inovatif oleh pelajar dan mahasiswa.',
                    'tanggal_mulai' => '2025-06-30',
                    'tanggal_selesai' => '2025-08-01', // +1 bulan lebih
                    'pamflet_lomba' => 'gamedev_cup.jpg',
                    'link_pendaftaran' => 'https://gdi.or.id/devcup',
                    'status_verifikasi' => 'Disetujui',
                    'biaya_pendaftaran' => 40000,
                    'hadiah' => 8500000,
                    'format_lomba' => 'online',
                    'tipe_lomba' => 'tim',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'user_id' => 3
                ],
                [
                    'nama_lomba' => 'Data Analytics Polinema Challenge',
                    'kategori_lomba' => 'akademik',
                    'tingkat_lomba' => 'politeknik',
                    'penyelenggara_lomba' => 'Jurusan Teknologi Informasi Polinema',
                    'deskripsi' => 'Lomba analisis data dan pembuatan dashboard visual berbasis studi kasus.',
                    'tanggal_mulai' => '2025-08-01',
                    'tanggal_selesai' => '2025-09-01', // +1 bulan
                    'pamflet_lomba' => 'dapc_polinema.jpg',
                    'link_pendaftaran' => 'https://polinema.ac.id/dapc',
                    'status_verifikasi' => 'Disetujui',
                    'biaya_pendaftaran' => 15000,
                    'hadiah' => 3000000,
                    'format_lomba' => 'offline',
                    'tipe_lomba' => 'individu',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'user_id' => 4
                ],
                [
                    'nama_lomba' => 'Virtual Robotics Competition',
                    'kategori_lomba' => 'akademik',
                    'tingkat_lomba' => 'kota',
                    'penyelenggara_lomba' => 'Dinas Pendidikan Kota Bandung',
                    'deskripsi' => 'Simulasi lomba robotik virtual untuk SMA/SMK dan mahasiswa awal.',
                    'tanggal_mulai' => '2025-06-25',
                    'tanggal_selesai' => '2025-07-05', // +2 minggu
                    'pamflet_lomba' => 'robotics_virtual.jpg',
                    'link_pendaftaran' => 'https://bandung.edu/robotics',
                    'status_verifikasi' => 'Disetujui',
                    'biaya_pendaftaran' => 0,
                    'hadiah' => 2500000,
                    'format_lomba' => 'online',
                    'tipe_lomba' => 'tim',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'user_id' => 1
                ],
                [
                    'nama_lomba' => 'Desain UI/UX untuk Aplikasi Kesehatan',
                    'kategori_lomba' => 'non-akademik',
                    'tingkat_lomba' => 'provinsi',
                    'penyelenggara_lomba' => 'Startup Digital Health Jatim',
                    'deskripsi' => 'Lomba desain antarmuka aplikasi mobile bertema kesehatan dan kebugaran.',
                    'tanggal_mulai' => '2025-07-15',
                    'tanggal_selesai' => '2025-08-01',
                    'pamflet_lomba' => 'uiux_health.jpg',
                    'link_pendaftaran' => 'https://startuphealth.id/lomba',
                    'status_verifikasi' => 'Disetujui',
                    'biaya_pendaftaran' => 10000,
                    'hadiah' => 3500000,
                    'format_lomba' => 'online',
                    'tipe_lomba' => 'individu',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'user_id' => 5
                ],
                [
                    'nama_lomba' => 'Smart Farming Technology Contest',
                    'kategori_lomba' => 'akademik',
                    'tingkat_lomba' => 'nasional',
                    'penyelenggara_lomba' => 'Balitbang Pertanian RI',
                    'deskripsi' => 'Kompetisi rancang sistem teknologi pertanian berbasis IoT dan data.',
                    'tanggal_mulai' => '2025-07-10',
                    'tanggal_selesai' => '2025-10-10',
                    'pamflet_lomba' => 'smartfarm_2024.jpg',
                    'link_pendaftaran' => 'https://balitbang.go.id/farm',
                    'status_verifikasi' => 'Disetujui',
                    'biaya_pendaftaran' => 50000,
                    'hadiah' => 9000000,
                    'format_lomba' => 'offline',
                    'tipe_lomba' => 'tim',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'user_id' => 2
                ],
                [
                    'nama_lomba' => 'Lomba UI Web Edukasi',
                    'kategori_lomba' => 'akademik',
                    'tingkat_lomba' => 'kota',
                    'penyelenggara_lomba' => 'Dinas Pendidikan Kota Malang',
                    'deskripsi' => 'Kompetisi desain antarmuka untuk web edukasi jenjang sekolah.',
                    'tanggal_mulai' => '2025-06-20',
                    'tanggal_selesai' => '2025-06-27',
                    'pamflet_lomba' => 'uiwedukasi_malang.jpg',
                    'link_pendaftaran' => 'https://diknasmlg.id/webedukasi',
                    'status_verifikasi' => 'Disetujui',
                    'biaya_pendaftaran' => 0,
                    'hadiah' => 2000000,
                    'format_lomba' => 'offline',
                    'tipe_lomba' => 'individu',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'user_id' => 3
                ],
                [
                    'nama_lomba' => 'Augmented Reality Design Contest',
                    'kategori_lomba' => 'akademik',
                    'tingkat_lomba' => 'nasional',
                    'penyelenggara_lomba' => 'AR Developer Society',
                    'deskripsi' => 'Lomba membuat aplikasi AR untuk edukasi atau promosi digital.',
                    'tanggal_mulai' => '2025-08-01',
                    'tanggal_selesai' => '2025-11-01',
                    'pamflet_lomba' => 'arcontest.jpg',
                    'link_pendaftaran' => 'https://ar-devsociety.org/lomba',
                    'status_verifikasi' => 'Disetujui',
                    'biaya_pendaftaran' => 30000,
                    'hadiah' => 6000000,
                    'format_lomba' => 'online',
                    'tipe_lomba' => 'tim',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'user_id' => 1
                ],
                [
                    'nama_lomba' => 'Digital Poster Kampanye Siber',
                    'kategori_lomba' => 'non-akademik',
                    'tingkat_lomba' => 'provinsi',
                    'penyelenggara_lomba' => 'Kominfo Provinsi Jatim',
                    'deskripsi' => 'Lomba desain poster digital untuk kampanye literasi keamanan siber.',
                    'tanggal_mulai' => '2025-07-15',
                    'tanggal_selesai' => '2025-08-20',
                    'pamflet_lomba' => 'poster_siber.jpg',
                    'link_pendaftaran' => 'https://kominfo.jatimprov.go.id/poster',
                    'status_verifikasi' => 'Disetujui',
                    'biaya_pendaftaran' => 10000,
                    'hadiah' => 2000000,
                    'format_lomba' => 'online',
                    'tipe_lomba' => 'individu',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'user_id' => 4
                ]
        ]);
    }
}